
name: unidocs
services:
  backend:
    build:
      context: ./server 
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=5433  
    ports:
      - 5000:5000
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
