
name: unidocs
services:
  document:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=document
    dns:
      - 8.8.8.8
    ports:
      - 5001:5000
    networks:
      - app-network

  folder:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=folder
    dns:
      - 8.8.8.8
    ports:
      - 5002:5000
    networks:
      - app-network

  pdf:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=pdf
    dns:
      - 8.8.8.8
    ports:
      - 5003:5000
    networks:
      - app-network

  user:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=user
    dns:
      - 8.8.8.8
    ports:
      - 5004:5000
    networks:
      - app-network

  auth:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=auth
    dns:
      - 8.8.8.8
    ports:
      - 5005:5000
    networks:
      - app-network

  upload:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/unidocs/server/uploads
      - ./server/unidocs-e4fc2cea1f64.json:/app/unidocs-e4fc2cea1f64.json
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.knzeiuvmewjpzgvdjmjh:Theterminator563@@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/app/unidocs-e4fc2cea1f64.json
      - SERVICE_TYPE=upload
    dns:
      - 8.8.8.8
    ports:
      - 5006:5000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - document
      - folder
      - pdf
      - user
      - auth
      - upload
    networks:
      - app-network
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
