version: '3.8'

services:
  backend:
    build:
      context: ./server # Path to the Node.js backend directory
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DATABASE}
      - DB_PORT=5432  
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
