worker_processes 1;

events {
   worker_connections 1024;
}

http {
  upstream document{
    server document:5000;
  }
  upstream folder{
    server folder:5000;
  }
  upstream pdf{
    server pdf:5000;
  }
  upstream user{
    server user:5000;
  }
  upstream auth{
    server auth:5000;
  }
  upstream upload {
    server upload:5000;
  }

  server {
    listen 80;

    location /document/ {
      proxy_pass http://document;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /folder/ {
      proxy_pass http://folder;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /pdf/ {
      proxy_pass http://pdf;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /user/ {
      proxy_pass http://user;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Cookie $http_cookie; 
    }
    location /auth/ {
      proxy_pass http://auth;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Cookie $http_cookie; 
    }
    location /uploads/ {
      proxy_pass http://upload;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
