---
title: "final projectt"
format: pdf
editor: visual
---

```{r}
library(readr)
library(forecast)
library(quantmod)
library(tseries)
library(dplyr)
library(corrplot)
library(vars)
library(car)
library(BVAR)

```

```{r}
dataset<- read.csv("c://users/pc/Downloads/indicator2.csv")
dataset <- dataset[rev(1:nrow(dataset)), ]
View(dataset)

```

```{r}
columns <- c("MONEY.SUPPLY", "RATE.OF.UNEMPLOYMENT", "CONSUMER.PRICE.INDEX","INTEREST.RATE","TD.BANK","BANK.OF.NOVASCOTIA","ROYAL.BANK.OF.CANADA")

```

```{r}
for (col in columns) {
  ts_data <- ts(dataset[[col]], start = c(2018, 1), frequency = 12)  
  adf_result <- adf.test(ts_data, alternative = "stationary")
  
  cat("\nADF Test Results for", col, ":\n")
  print(adf_result)
}
```

```{r}
View(dataset)
```

```{r}
# Loop through each column and apply differencing
for (col in columns) {
  # Check if the column has enough data to perform the test
  ts_data <- ts(dataset[[col]], start = c(2018, 1), frequency = 12)  
  
  # Apply differencing to make the series stationary (1st difference)
  ts_data_diff <- diff(ts_data, differences = 2)
  
  dataset[[col]] <- c(NA, NA, ts_data_diff) 
  
  # Perform the ADF test on the differenced series
  adf_result_diff <- adf.test(ts_data_diff, alternative = "stationary")
  
  cat("\nADF Test Results for", col, "after differencing:\n")
  print(adf_result_diff)
}


```

```{r}
View(dataset)
```

```{r}

dataset$MONEY.SUPPLY[dataset$MONEY.SUPPLY <= 0] <- NA

dataset <- na.omit(dataset)

ts_data_log <- log(ts(dataset$MONEY.SUPPLY, start = c(2018, 1), frequency = 12))

ts_data_log_diff <- diff(ts_data_log, differences = 1)

dataset$MONEY.SUPPLY_DIFF <- c(NA, ts_data_log_diff)


adf_result_log_diff <- adf.test(ts_data_log_diff, alternative = "stationary")

print(adf_result_log_diff)
```

```{r}
View(dataset)
```

```{r}
max_lag <- 6

for (col in columns) {
  for (i in 1:max_lag) {
    dataset[[paste0(col, "_lag", i)]] <- dplyr::lag(dataset[[col]], n = i)
  }
}

```

```{r}
columns <- c(
  "MONEY.SUPPLY", "MONEY.SUPPLY_lag1", "MONEY.SUPPLY_lag2", "MONEY.SUPPLY_lag3", "MONEY.SUPPLY_lag4", "MONEY.SUPPLY_lag5", "MONEY.SUPPLY_lag6",
  "RATE.OF.UNEMPLOYMENT", "RATE.OF.UNEMPLOYMENT_lag1", "RATE.OF.UNEMPLOYMENT_lag2", "RATE.OF.UNEMPLOYMENT_lag3", "RATE.OF.UNEMPLOYMENT_lag4", "RATE.OF.UNEMPLOYMENT_lag5", "RATE.OF.UNEMPLOYMENT_lag6",
  "CONSUMER.PRICE.INDEX", "CONSUMER.PRICE.INDEX_lag1", "CONSUMER.PRICE.INDEX_lag2", "CONSUMER.PRICE.INDEX_lag3", "CONSUMER.PRICE.INDEX_lag4", "CONSUMER.PRICE.INDEX_lag5", "CONSUMER.PRICE.INDEX_lag6",
  "INTEREST.RATE", "INTEREST.RATE_lag1", "INTEREST.RATE_lag2", "INTEREST.RATE_lag3", "INTEREST.RATE_lag4", "INTEREST.RATE_lag5", "INTEREST.RATE_lag6",
  "TD.BANK", "TD.BANK_lag1", "TD.BANK_lag2", "TD.BANK_lag3", "TD.BANK_lag4", "TD.BANK_lag5", "TD.BANK_lag6",
  "BANK.OF.NOVASCOTIA", "BANK.OF.NOVASCOTIA_lag1", "BANK.OF.NOVASCOTIA_lag2", "BANK.OF.NOVASCOTIA_lag3", "BANK.OF.NOVASCOTIA_lag4", "BANK.OF.NOVASCOTIA_lag5", "BANK.OF.NOVASCOTIA_lag6",
  "ROYAL.BANK.OF.CANADA", "ROYAL.BANK.OF.CANADA_lag1", "ROYAL.BANK.OF.CANADA_lag2", "ROYAL.BANK.OF.CANADA_lag3", "ROYAL.BANK.OF.CANADA_lag4", "ROYAL.BANK.OF.CANADA_lag5", "ROYAL.BANK.OF.CANADA_lag6"
)


```

```{r}
correlation_matrix <- cor(dataset[, columns], use = "complete.obs")
print(correlation_matrix)
```

```{r}
corrplot(correlation_matrix, method = "pie", type = "upper", tl.col = "black", tl.srt = 45)

```

```{r}
write.csv(correlation_matrix, "correlation_matrix_with_lags.csv")

```

```{r}
View(correlation_matrix)
```

```{r}
adf_result <- adf.test(dataset[, columns[1]], alternative = "stationary")
print(adf_result)

# Difference the data if non-stationary
if (adf_result$p.value > 0.05) {
  dataset_diff <- diff(dataset[, columns[1]])
} else {
  dataset_diff <- dataset[, columns[1]]
}

# Fit ARIMA on differenced data
arima_model <- auto.arima(dataset_diff)
print(arima_model)
```

```{r}

columns <- c("MONEY.SUPPLY", "RATE.OF.UNEMPLOYMENT", "CONSUMER.PRICE.INDEX","INTEREST.RATE","TD.BANK","BANK.OF.NOVASCOTIA","ROYAL.BANK.OF.CANADA")

for (col in columns) {
  adf_test <- adf.test(dataset[[col]], alternative = "stationary")
  cat("ADF Test for", col, ":\n")
  print(adf_test)
}

library(vars)
lag_selection <- VARselect(dataset[, columns], lag.max = 10)
print(lag_selection)
optimal_lag <- lag_selection$selection["AIC(n)"]

var_model <- VAR(dataset[, columns], p = 3)
print(var_model)
cor_matrix <- cor(dataset[, columns])
print(cor_matrix)

```

```{r}
roots <- roots(var_model, modulus = TRUE)
print(roots)
```

```{r}
causality(var_model, cause = "MONEY.SUPPLY") 

causality(var_model, cause = "RATE.OF.UNEMPLOYMENT")  

causality(var_model, cause = "CONSUMER.PRICE.INDEX")  

causality(var_model, cause = "INTEREST.RATE")
```
